schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "colmap_rig_addon"
version = "0.2.1"
name = "COLMAP Rig Export & Batch Render"
tagline = "Export COLMAP rig JSON and batch-render per-camera frames"
maintainer = "Achim A."
# Supported types: "add-on", "theme"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/add-std-paper-size/"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Import-Export", "Render", "Camera"]

blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
# Optional: required by some licenses.
copyright = [
  "2024-2025 Achim A.",
  "piexif library: Copyright (c) 2014, 2015 hMatoba (MIT License)",
]

# # Optional: list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# # Other supported platforms: "windows-arm64", "macos-x64"

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
  "./wheels/piexif-1.1.3-py2.py3-none-any.whl",
]

# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
#
# [permissions]
# network = "Need to sync motion-capture data to server"
files = "Export rig JSON specified output directory."
# clipboard = "Copy and paste bone transforms"

# # Optional: advanced build settings.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
[build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
paths_exclude_pattern = [
  "__pycache__/",
  "/images/",
  "/.git*/",
  "/.vscode/",
  "/*.zip",
  ".gitignore",
  "README.md",
  "build.ps1",
  "/wheels/LICENSE-piexif.txt"
]